intercity_route:
  regexp:
    - '(найди )?(билеты? )?(от |из |с )?(?P<from>{{CITY}}) (до |в |к |на )?(?P<to>{{CITY}})( {{_WHEN}})?'

slots_filling:
  regexp:
    - '{{_WHEN}}'
    - '{{FROM_PRP}}?(?P<from>{{CITY}})'
    - '{{TO_PRP}}?(?P<to>{{CITY}})'

station:
  regexp:
    - '{{FROM_PRP}}(?P<from>{{_STATION_WIDE}})'
    - '{{TO_PRP}}(?P<to>{{_STATION_WIDE}})'
    - '(?P<fromto>{{_STATION_WIDE}})'

suburb_route:
  regexp:
    - '(найди )?(билеты? )?({{_SUBURBAN_PREFIX}} )?{{FROM_PRP}}?(?P<from>{{_STATION}}) {{TO_PRP}}?(?P<to>{{_STATION}})( {{_WHEN}})?'
    - '(найди )?(билеты? )?({{_SUBURBAN_PREFIX}} )?{{TO_PRP}}(?P<to>{{_STATION_WIDE}}){{FROM_PRP}}(?P<from>{{_STATION_WIDE}})( {{_WHEN}})?'

