intercity_route:
  regexp:
    - '(найди )?(билеты? )?(от |из |с )?(?P<from>{{CITY}}) (до |в |к |на )?(?P<to>{{CITY}})( {{_WHEN}})?'

slots_filling:
  regexp:
    - '{{_WHEN}}'
    - '{{FROM_PRP}}?(?P<from>{{CITY}})'
    - '{{TO_PRP}}?(?P<to>{{CITY}})'

suburb_ellipsis:
  regexp:
    - '{{ELLIPSIS}}{{FROM_PRP}}(?P<from>{{_STATION_WIDE}})'
    - '{{ELLIPSIS}}{{TO_PRP}}(?P<to>{{_STATION_WIDE}})'
    - '{{ELLIPSIS}}(?P<fromto>{{_STATION_WIDE}})'
    - '{{ELLIPSIS}}{{_WHEN}}'
    - '{{ELLIPSIS}}{{_BACK}}'
    - '{{ELLIPSIS}}{{FROM_PRP}}?(?P<from>{{_STATION}}) {{TO_PRP}}?(?P<to>{{_STATION}})?( {{_WHEN}})$'

suburb_route:
  regexp:
    - '(найди )?(билеты? )?({{_SUBURBAN_PREFIX}} ){{FROM_PRP}}?(?P<from>{{_STATION}})?\s*{{TO_PRP}}?(?P<to>{{_STATION}})?( {{_WHEN}})?$'
    #- '(найди )?(билеты? )?({{_SUBURBAN_PREFIX}} )?{{TO_PRP}}(?P<to>{{_STATION_WIDE}}){{FROM_PRP}}(?P<from>{{_STATION_WIDE}})( {{_WHEN}})?$'

confirm_purchase:
  regexp:
    - '((да|давай|купи|купить)\s)+'

both_sides:
  regexp:
    - '(купи(ть)? )?(билеты? )?(туда и обратно|в обе стороны)'

one_side:
  regexp:
    - '(купи(ть)? )?(билеты? )?(только туда|в одном направлении|без обратного|в одну сторону)'
